### ISSUE TITLE
Having trouble with npm start

### ISSUE THREAD

**Issue by JudeUk** [insidesherpa/JPMC-tech-task-2-PY3#27] opened 2019-12-27 00:01 UTC
Dear Team,
please help out, after i successfully execute npm start command i get the below message on my command screen, also i am unable to stream data as the url- localhost:3000 returns a similar error to that displayed on the command screen.
![JPmorgan](https://user-images.githubusercontent.com/31444432/71494049-6a07ba80-2844-11ea-931e-2a81d111a846.PNG)
![JPmorgan2](https://user-images.githubusercontent.com/31444432/71494055-73912280-2844-11ea-92f3-ddfa1f358759.PNG)

**Comment by jbf-insidesherpa** [comment] 2019-12-29 10:03
@JudeUk this is most likely caused by you having problems with **npm install** The troubleshooting slides should be able to help you in resolving problems for **npm install** you just have to find which case it is you're getting. If none of those help feel free to reopen this issue and include the error you're getting

**Closed by jbf-insidesherpa** 2019-12-29 10:03 UTC

**Comment by JudeUk** [comment] 2019-12-30 08:14
@jbf-insidesherpa Dear Jbf, thank you for your response, your contribution was helpful in resolving what the issue was, however these steps below will be helpful if ever anyone else faces the same problem on windows.

1. Install node.msi on windows instead, rather than by nvm. select the option to install python 2 as 
     well, this will install npm on your machine too. Now npm will be recognised on your cmd.
2. As a result of step one you can run "npm install" command in your project repo on your machine. 
    this is will install npm in your repository, so you can do 
    step 3 successfully.
3.run the "npm start" command to start the server successfully.
![npm_success](https://user-images.githubusercontent.com/31444432/71573536-b5d88f00-2ae4-11ea-967a-07a7fd80fdc5.PNG)
